//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int Branch_ID { get; set; }
        public string Branch_Address { get; set; }
        public Nullable<int> Contact_Number { get; set; }
        public string City { get; set; }
    }
}
