//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Contact { get; set; }
        public Nullable<System.DateTime> Datee { get; set; }
        public Nullable<System.TimeSpan> Timee { get; set; }
        public string Form_Of_Payment { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
